### ISSUE TITLE
Home Manager as NixOS Module

### ISSUE THREAD

**Issue by ghost** [ehllie/ez-configs#13]
Can you add an option to set up Home Manager with a NixOS module? I'm having trouble getting Home Manager to work on its own when I install NixOS using the flake I created.

**Comment by ehllie** [comment]
That's precisely what [`userHomeModules`](https://flake.parts/options/ez-configs#opt-ezConfigs.nixos.hosts._name_.userHomeModules) is for

**Comment by ghost** [comment]
Thanks for the clarification! I'll look into userHomeModules to get it working. Appreciate your help!
