### ISSUE TITLE
Per host nixpkgs config?

### ISSUE THREAD

**Issue by lpchaim** [ehllie/ez-configs#14]
Just started toying with this and I'm wondering if it's possible to set a custom pkgs instance for each host. My use case is I'd like to set nixpkgs options like allowUnfree or cudaSupport at the host level. If it's not supported, would a PR implementing something similar to the existing standalone home pkgs override for nixos configurations be welcome? I'm thinking `ezConfigs.nixos.hosts.<name>.pkgs`, perhaps with an optional `ezConfigs.pkgs` defaulting to the current behavior to use as a default.

On that note, what's the usual way to set options such as these at all? Say, just setting allowUnfree globally, for instance. I can't seem to figure it out on my own, maybe because I'm also new to flake-parts as a whole :sweat_smile:

**Comment by lpchaim** [comment]
I just realized you can easily tweak that by setting `nixpkgs.config` in a module or wherever else. My coming from [snowfall-lib](https://snowfall.org/reference/lib/) made me think it wouldn't work, because last I checked that didn't work there.

**Comment by karpfediem** [comment]
I wanted to consistently apply the same baseline config + overlays to any instances of `pkgs` that i was using.

I came up with a patch like this for my own use: https://github.com/ehllie/ez-configs/compare/main...karpfediem:ez-configs:badidea which allows me to pass extraModules to be imported at various levels (also per host).

I'm using it with a flake-module that exports my nixpkgs config + overlay as `flake.nixosModules.nixpkgs` module like this: https://github.com/karpfediem/devices/blob/84fe858a75c21b8d79caba779d7525673aa2d482/nixpkgs/default.nix

And then i can simply pass my modules in with extraModules options:
```nix
# flake.nix
        # ...
        ezConfigs = {
          root = ./.;
          globalArgs = { inherit inputs; };
          # Can include modules everywhere
          extraModules = [ self.nixosModules.nixpkgs ];
          # Can be overwritten per configType
          home.extraModules = [ self.nixosModules.nixpkgs ];
          nixos.extraModules = [ self.nixosModules.nixpkgs ];
          darwin.extraModules = [ self.nixosModules.nixpkgs ];

          nixos.hosts = {
            aquarium = {
              userHomeModules = [ "carp" ];
              # Can be amended per host
              extraModules = [ self.nixosModules.nixpkgs ];
            };
          };
        };
        # ...
```

I might clean this up to upstream if there is any interest. 
But it feels like a bit of a hack and too many options lol
